# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/Documents/c++/Projects/TextToPDF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/Documents/c++/Projects/TextToPDF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Documents/c++/Projects/TextToPDF/CMakeFiles /home/david/Documents/c++/Projects/TextToPDF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/Documents/c++/Projects/TextToPDF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/TextToPDF

# Build rule for target.
bin/TextToPDF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/TextToPDF
.PHONY : bin/TextToPDF

# fast build rule for target.
bin/TextToPDF/fast:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/build
.PHONY : bin/TextToPDF/fast

src/EntryPoint.o: src/EntryPoint.cpp.o

.PHONY : src/EntryPoint.o

# target to build an object file
src/EntryPoint.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/EntryPoint.cpp.o
.PHONY : src/EntryPoint.cpp.o

src/EntryPoint.i: src/EntryPoint.cpp.i

.PHONY : src/EntryPoint.i

# target to preprocess a source file
src/EntryPoint.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/EntryPoint.cpp.i
.PHONY : src/EntryPoint.cpp.i

src/EntryPoint.s: src/EntryPoint.cpp.s

.PHONY : src/EntryPoint.s

# target to generate assembly for a file
src/EntryPoint.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/EntryPoint.cpp.s
.PHONY : src/EntryPoint.cpp.s

src/Font.o: src/Font.cpp.o

.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i

.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s

.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/Layout.o: src/Layout.cpp.o

.PHONY : src/Layout.o

# target to build an object file
src/Layout.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Layout.cpp.o
.PHONY : src/Layout.cpp.o

src/Layout.i: src/Layout.cpp.i

.PHONY : src/Layout.i

# target to preprocess a source file
src/Layout.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Layout.cpp.i
.PHONY : src/Layout.cpp.i

src/Layout.s: src/Layout.cpp.s

.PHONY : src/Layout.s

# target to generate assembly for a file
src/Layout.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Layout.cpp.s
.PHONY : src/Layout.cpp.s

src/Page.o: src/Page.cpp.o

.PHONY : src/Page.o

# target to build an object file
src/Page.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Page.cpp.o
.PHONY : src/Page.cpp.o

src/Page.i: src/Page.cpp.i

.PHONY : src/Page.i

# target to preprocess a source file
src/Page.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Page.cpp.i
.PHONY : src/Page.cpp.i

src/Page.s: src/Page.cpp.s

.PHONY : src/Page.s

# target to generate assembly for a file
src/Page.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/Page.cpp.s
.PHONY : src/Page.cpp.s

src/PageContent.o: src/PageContent.cpp.o

.PHONY : src/PageContent.o

# target to build an object file
src/PageContent.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/PageContent.cpp.o
.PHONY : src/PageContent.cpp.o

src/PageContent.i: src/PageContent.cpp.i

.PHONY : src/PageContent.i

# target to preprocess a source file
src/PageContent.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/PageContent.cpp.i
.PHONY : src/PageContent.cpp.i

src/PageContent.s: src/PageContent.cpp.s

.PHONY : src/PageContent.s

# target to generate assembly for a file
src/PageContent.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/PageContent.cpp.s
.PHONY : src/PageContent.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/xref.o: src/xref.cpp.o

.PHONY : src/xref.o

# target to build an object file
src/xref.cpp.o:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/xref.cpp.o
.PHONY : src/xref.cpp.o

src/xref.i: src/xref.cpp.i

.PHONY : src/xref.i

# target to preprocess a source file
src/xref.cpp.i:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/xref.cpp.i
.PHONY : src/xref.cpp.i

src/xref.s: src/xref.cpp.s

.PHONY : src/xref.s

# target to generate assembly for a file
src/xref.cpp.s:
	$(MAKE) -f CMakeFiles/bin/TextToPDF.dir/build.make CMakeFiles/bin/TextToPDF.dir/src/xref.cpp.s
.PHONY : src/xref.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... bin/TextToPDF"
	@echo "... src/EntryPoint.o"
	@echo "... src/EntryPoint.i"
	@echo "... src/EntryPoint.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/Layout.o"
	@echo "... src/Layout.i"
	@echo "... src/Layout.s"
	@echo "... src/Page.o"
	@echo "... src/Page.i"
	@echo "... src/Page.s"
	@echo "... src/PageContent.o"
	@echo "... src/PageContent.i"
	@echo "... src/PageContent.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/xref.o"
	@echo "... src/xref.i"
	@echo "... src/xref.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

